cd ~/.tmuxinator
tmuxinator home
tmuxinator foo
tmuxinator dynos_login
tmuxinator mgmt_api
tmuxinator mgmt_ui
tmuxinator editor
tmuxinator dynos_viewer
tmuxinator mongo
tmuxinator admin_ui
tmuxinator dynos_viewer
